# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Terraform fmt
        id: fmt
        env:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
         curl https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip -o terraform_0.13.5_linux_amd64.zip
         sudo apt-get install unzip -y
         unzip terraform_0.13.5_linux_amd64.zip
         sudo mv terraform /usr/local/bin/
         cd deploy/staging
         pwd & ls -l
         terraform --version
         terraform init 
         echo "################PLAN################"
         terraform plan
         echo "################APPLY################"
         terraform apply --auto-approve

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd deploy
          pwd
